import type { Profile, Project } from "@/lib/types";

export const mockProfile: Profile = {
    id: "1",
    name: "Đào Ngọc Thạch",
    role: "FrontEnd Developer",
    description:
        "Passionate FrontEnd Developer with hands-on experience building cross-platform mobile apps and modern web applications. Skilled in the React ecosystem, from React JS and Next.js for web to React Native for mobile. Experienced with cloud services like Supabase and Firebase to deliver scalable, real-time solutions.",
    location: "Vietnam",
    github_url: "https://github.com/Daongocthach",
    linkedin_url: "https://www.linkedin.com/in/daongocthach",
    email: "thachdn@finepro.net",
    avatar_url: "/images/logo.png",
    skills: [
        "React JS",
        "React Native",
        "Next.js",
        "Supabase",
        "Firebase",
        "Node.js",
    ],
    updated_at: "2026-02-25T00:00:00.000Z",
};

export const mockProjects: Project[] = [
    {
        id: "1",
        slug: "check-calo",
        name: "Check Calo",
        description: "Ứng dụng di động theo dõi calo và bữa ăn bằng ảnh, hỗ trợ quản lý dinh dưỡng, xác thực người dùng, đồng bộ dữ liệu và trải nghiệm đa ngôn ngữ trên iOS/Android.",
        project_url: null,
        github_url: null,
        image_url: "/images/projects/check-calo/checkcalo-banner.webp",
        screenshots: [
            "/images/projects/check-calo/checkcalo-banner.webp",
            "/images/projects/check-calo/check-calo-1.webp",
            "/images/projects/check-calo/check-calo-2.webp",
            "/images/projects/check-calo/check-calo-3.webp",
            "/images/projects/check-calo/check-calo-4.webp",
            "/images/projects/check-calo/check-calo-5.webp",
            "/images/projects/check-calo/check-calo-6.webp",
            "/images/projects/check-calo/check-calo-7.webp",
            "/images/projects/check-calo/check-calo-8.webp",
        ],
        technologies: ["React Native", "Expo SDK 55", "TypeScript", "Supabase", "React Query", "Zustand", "react-native-unistyles", "Axios", "react-i18next", "MMKV"],
        sort_order: 1,
        created_at: "2026-03-01T00:00:00.000Z",
        type: "Mobile app template / ứng dụng di động",
        role: "Mobile App Developer",
        duration: "Development phase",
        team_size: "Personal Project",
        launched: "v1.0.0",
        stats: [
            { label: "Trải nghiệm", value: "Mượt mà" },
            { label: "Nền tảng", value: "iOS & Android" },
            { label: "Công nghệ", value: "Modern Stack" }
        ],
        features: [
            "Đăng nhập và xác thực",
            "Theo dõi calo/bữa ăn bằng ảnh",
            "Giao diện sáng/tối",
            "Đa ngôn ngữ Anh - Việt",
            "Quản lý server state với React Query",
            "Bộ component dùng chung",
            "Kiểm thử và linting sẵn có"
        ],
        challenge: "Cần một nền tảng khởi đầu ổn định thay vì dựng app từ đầu. Phải giữ kiến trúc rõ ràng để dễ mở rộng tính năng. Cần hỗ trợ auth, theme, i18n ngay từ đầu.",
        solution: "Tích hợp Expo Router để tổ chức điều hướng. Dùng Supabase cho xác thực. Dùng React Query và Zustand để tách server state và client state. Dùng MMKV để lưu trữ cục bộ."
    },
    {
        id: "2",
        slug: "fineprojects",
        name: "Fineprojects",
        description: "A mobile workspace app for managing projects, meetings, leave requests, overtime, notifications, and internal operations in one platform.",
        project_url: 'https://apps.apple.com/vn/app/fineprojects/id6749673116?l=vi',
        github_url: null,
        image_url: "/images/projects/fineprojects/fineprojects-banner.webp",
        screenshots: [
            "/images/projects/fineprojects/fineprojects-banner.webp",
            "/images/projects/fineprojects/fineprojects-1.webp",
            "/images/projects/fineprojects/fineprojects-2.webp",
            "/images/projects/fineprojects/fineprojects-3.webp",
            "/images/projects/fineprojects/fineprojects-4.webp",
            "/images/projects/fineprojects/fineprojects-5.webp",
            "/images/projects/fineprojects/fineprojects-6.webp",
            "/images/projects/fineprojects/fineprojects-7.webp",
        ],
        technologies: ["Expo", "React Native", "TypeScript", "Zustand", "TanStack Query", "Firebase", "Socket.io"],
        sort_order: 2,
        created_at: "2025-01-01T00:00:00.000Z",
        type: "Mobile enterprise internal management app",
        role: "Mobile Developer",
        duration: "2025 - 2026",
        team_size: "4 - 6 members",
        launched: "Internal release",
        stats: [
            { label: "Productivity Increase", value: "35%" },
            { label: "Active Users", value: "100+" },
            { label: "Customers", value: "10+" }
        ],
        features: [
            "Project, task, and progress management",
            "Meeting scheduling and room management",
            "Leave request and approval workflow",
            "Overtime reports and timesheets",
            "Real-time notifications and reminders",
            "User profile and role-based access"
        ],
        challenge: "Business workflows were spread across multiple tools. It was difficult to track progress and status in real time. Teams needed better coordination between project, HR, and management workflows.",
        solution: "Built a centralized mobile app for core operational workflows. Added real-time data sync and instant notifications. Designed clear permissions and streamlined user flows to reduce friction."
    },
    {
        id: "3",
        slug: "fine-detection",
        name: "Fine Detection Mobile App",
        description: "A React Native (Expo) mobile app for manufacturing quality control and defect inspection workflows.",
        project_url: null,
        github_url: null,
        image_url: "/images/projects/fine-detection/finedetection-banner.webp",
        screenshots: [
            "/images/projects/fine-detection/finedetection-banner.webp",
            "/images/projects/fine-detection/fine-detection-1.webp",
            "/images/projects/fine-detection/fine-detection-2.webp",
            "/images/projects/fine-detection/fine-detection-3.webp",
            "/images/projects/fine-detection/fine-detection-4.webp",
            "/images/projects/fine-detection/fine-detection-5.webp",
            "/images/projects/fine-detection/fine-detection-6.webp",
        ],
        technologies: ["Expo", "React Native", "TypeScript", "Expo Router", "TanStack Query", "Zustand", "i18next", "Sentry", "Maestro", "react-native-nfc-manager"],
        sort_order: 3,
        created_at: "2026-01-29T00:00:00.000Z",
        type: "B2B manufacturing quality control mobile application",
        role: "Mobile App Developer / React Native Engineer",
        duration: "2026-01-29 to 2026-04-21",
        team_size: "Small cross-functional team",
        launched: "2026-04-21",
        stats: [
            { label: "Productivity", value: "Streamlined" },
            { label: "Users", value: "Internal" },
            { label: "Deployment", value: "Enterprise" }
        ],
        features: [
            "NFC or credential-based authentication",
            "Defect settings create/edit",
            "Defect item capture and analysis flow",
            "Product code scanning and image evidence capture",
            "Approval workflow and status updates",
            "Form management",
            "History search and filters",
            "Multilingual UI",
            "Maestro E2E test flows"
        ],
        challenge: "Digitizing a manual defect inspection workflow into a mobile-first experience. Supporting multiple user roles such as operators, supervisors, and reviewers.",
        solution: "Built a React Native app with Expo Router. Implemented defect capture flows with image upload, code scanning, and form logic. Added localization for multiple languages."
    },
    {
        id: "4",
        slug: "finetalent",
        name: "Tuyển Dụng (Finetalent)",
        description: "Ứng dụng di động Expo/React Native cho quy trình ứng tuyển, quét QR căn cước, nhập hồ sơ nhiều bước và upload CV cho ứng viên.",
        project_url: null,
        github_url: null,
        image_url: "/images/projects/finetalent/finetalent-banner.webp",
        screenshots: [
            "/images/projects/finetalent/finetalent-banner.webp",
            "/images/projects/finetalent/finetalent-1.webp",
            "/images/projects/finetalent/finetalent-2.webp",
            "/images/projects/finetalent/finetalent-3.webp",
            "/images/projects/finetalent/finetalent-4.webp",
            "/images/projects/finetalent/finetalent-5.webp",
            "/images/projects/finetalent/finetalent-6.webp",
            "/images/projects/finetalent/finetalent-7.webp",
        ],
        technologies: ["Expo / React Native", "TypeScript", "Expo Router", "Zustand", "React Query", "React Hook Form", "Zod", "Axios", "Supabase", "react-native-unistyles", "Camera / QR scanning", "MMKV", "i18next"],
        sort_order: 4,
        created_at: "2026-02-01T00:00:00.000Z",
        type: "Ứng dụng di động tuyển dụng",
        role: "Phát triển mobile app",
        duration: "Đang phát triển",
        team_size: "Finepro Automation",
        launched: "Sắp ra mắt",
        stats: [
            { label: "Tăng năng suất", value: "Đang cập nhật" },
            { label: "Người dùng active", value: "Đang cập nhật" },
            { label: "Khách hàng", value: "Đang cập nhật" }
        ],
        features: [
            "Form ứng tuyển nhiều bước",
            "Quét mã QR ID card",
            "Tự động điền thông tin từ dữ liệu quét",
            "Upload CV",
            "Màn hình xác nhận nộp hồ sơ thành công",
            "Hỗ trợ đa ngôn ngữ",
            "Lưu trạng thái form và điều hướng theo luồng"
        ],
        challenge: "Thiết kế luồng ứng tuyển nhiều bước với nhiều trường dữ liệu và validate chặt chẽ. Tích hợp quét QR để tự động điền thông tin ứng viên. Xử lý upload CV cùng với tạo hồ sơ ứng viên qua API.",
        solution: "Sử dụng Expo Router để tách màn hình theo luồng rõ ràng. Dùng React Hook Form kết hợp Zod để validate. Tích hợp camera/QR scanner để đọc dữ liệu từ ID card."
    },
    {
        id: "5",
        slug: "finetag",
        name: "Finetag",
        description: "Ứng dụng di động Expo/React Native cho quét NFC, Bluetooth, QR/DMC, xác minh thiết bị, kiểm tra checklist, ghi thẻ và nhận thông báo cho quy trình vận hành.",
        project_url: null,
        github_url: null,
        image_url: "/images/projects/finetag/finetag-banner.webp",
        screenshots: [
            "/images/projects/finetag/finetag-banner.webp",
            "/images/projects/finetag/finetag-1.webp",
            "/images/projects/finetag/finetag-2.webp",
            "/images/projects/finetag/finetag-3.webp",
            "/images/projects/finetag/finetag-4.webp",
            "/images/projects/finetag/finetag-5.webp",
            "/images/projects/finetag/finetag-6.webp",
            "/images/projects/finetag/finetag-7.webp",
            "/images/projects/finetag/finetag-8.webp",
            "/images/projects/finetag/finetag-9.webp",
            "/images/projects/finetag/finetag-10.webp",
        ],
        technologies: ["Expo / React Native", "TypeScript", "React Navigation / Expo Router", "Zustand", "React Query", "NFC, Bluetooth, Camera", "REST API, Socket.IO"],
        sort_order: 5,
        created_at: "2026-01-15T00:00:00.000Z",
        type: "Ứng dụng di động doanh nghiệp",
        role: "Phát triển mobile app",
        duration: "3 tháng",
        team_size: "Finepro Automation",
        launched: "12 tháng 04 năm 2026",
        stats: [
            { label: "Tăng năng suất", value: "35%" },
            { label: "Người dùng active", value: "100+" },
            { label: "Khách hàng", value: "20+" }
        ],
        features: [
            "Quét và ghi NFC tag",
            "Quét barcode / QR / DMC tray",
            "Kết nối và quản lý thiết bị Bluetooth",
            "Kiểm tra checklist thiết bị",
            "Xem chi tiết và lịch sử kiểm tra",
            "Nhận thông báo đẩy",
            "Quản lý danh sách thiết bị và trạng thái",
            "Hỗ trợ đa ngôn ngữ"
        ],
        challenge: "Kết hợp nhiều phương thức nhận diện như NFC, BLE, QR và camera. Đảm bảo đồng bộ dữ liệu thời gian thực và xử lý trạng thái thiết bị. Quản lý quyền truy cập phần cứng trên iOS và Android.",
        solution: "Sử dụng Expo/React Native để phát triển đa nền tảng. Tích hợp react-native-nfc-manager, react-native-ble-plx và vision camera. Dùng React Query và Socket.IO để đồng bộ dữ liệu."
    }
];